[build]
command = "npm run build"
publish = "client/dist"
base = "practice-timer"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "10" 