[build]
  base = "."
  command = "cd metronome && npm ci && npm run build"
  publish = "metronome/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 