[build]
  base = "."
  command = "cd metronome && npm install && npm run build"
  publish = "metronome/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 